# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dr. Michael Lesniak's blog
email: mail@mlesniak.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage of Dr. Michael Lesniak (34119 Kassel, Germany). I'm a software developer with heart and soul, working for [Micromata](http://www.micromata.de) in [Kassel](https://en.wikipedia.org/wiki/Kassel) on different automotive, logistics and health care projects. While I'm specialized on Big Data technologies and SAP HCP I also enjoy all other aspects of software development (architecture, clean code, code quality).

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mlesniak.com" # the base hostname & protocol for your site
twitter_username: mlesniak
github_username:  mlesniak

# Build settings
markdown: kramdown
